run_tests:
  before_script:
    - echo "prepare test data"
  script:
    - echo "run tests..."
  after_script:
    - echo "clean up scripts"

build_image:
  script:
    - echo "building image"
    - echo "push to docker registerys"
