stages:
  - test
  - build

run_tests:
  stage: test
  script:
    - echo "run tests..."

build_image:
  stage: build
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD registry.gitlab.com
  script:
    - docker build -t registry.gitlab.com/a.edareheydarabadi/test:1.0 .
    - docker push registry.gitlab.com/a.edareheydarabadi/test:1.0